version: 2.1

workflows:
    symfony-php8.0+:
        jobs:
            -   build:
                    name: php-<<matrix.php_version>>-symfony-<< matrix.symfony_version >>
                    matrix:
                        parameters:
                            php_version: [ "8.0", "8.1", "8.2", "8.3", "8.4" ]
                            symfony_version: [ "5.4", "6.4", "7.1" ]
                        exclude:
                            # Symfony 6.4 requires PHP 8.1+
                            -   php_version: "8.0"
                                symfony_version: "6.4"
                            # Symfony 7.x requires PHP 8.2+
                            -   php_version: "8.0"
                                symfony_version: "7.1"
                            -   php_version: "8.1"
                                symfony_version: "7.1"

jobs:
    build:
        parameters:
            symfony_version:
                type: string
            php_version:
                type: string
        docker:
            -   image: cimg/php:<< parameters.php_version >>

        steps:
            - checkout

            # Install specific Symfony version
            -   run: |
                    grep -o -E '"(symfony/[^"]+)"' composer.json | \
                    grep -v -E '(symfony/flex)' | \
                    xargs printf '%s:<< parameters.symfony_version >>.* ' | \
                    xargs composer require --no-interaction --no-update || true

            # Adjust dependencies based on PHP version
            -   run: |
                    # Remove deptrac on PHP 8.0 (requires PHP 8.1+)
                    if [ "<< parameters.php_version >>" = "8.0" ]; then
                        composer remove deptrac/deptrac --dev --no-update --no-interaction
                    fi

                    # On PHP 8.4: Upgrade PHPStan to 2.x and remove Rector (PHPStan 1.x doesn't support PHP 8.4)
                    if [ "<< parameters.php_version >>" = "8.4" ]; then
                        composer remove rector/rector --dev --no-update --no-interaction
                        composer require phpstan/phpstan:"^2.0" phpstan/phpstan-symfony:"^2.0" --dev --no-update --no-interaction
                    fi

            # Test with prefer-lowest (oldest compatible dependencies)
            -   run: composer update --no-interaction --prefer-lowest --prefer-stable
            -   run: vendor/bin/phpunit --no-coverage
            -   run: composer ecs
            -   run: composer phpstan
            -   run: |
                    if [ -f vendor/bin/deptrac ]; then
                        composer deptrac
                    fi
            -   run: |
                    if [ -f vendor/bin/rector ]; then
                        composer rector
                    fi

            # Test with prefer-stable (latest compatible dependencies)
            -   run: composer update --no-interaction --prefer-stable
            -   run: vendor/bin/phpunit --no-coverage
            -   run: composer ecs
            -   run: composer phpstan
            -   run: |
                    if [ -f vendor/bin/deptrac ]; then
                        composer deptrac
                    fi
            -   run: |
                    if [ -f vendor/bin/rector ]; then
                        composer rector
                    fi
