services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # URL Builder
    ThreeBrs\ImgproxyBundle\Imagine\ImgproxyUrlBuilder:
        arguments:
            $baseUrl: '%threebrs_imgproxy.base_url%'
            $sourceBaseUrl: '%threebrs_imgproxy.source_base_url%'
            $sourcePrefix: '%threebrs_imgproxy.source_prefix%'
            $key: '%threebrs_imgproxy.key%'
            $salt: '%threebrs_imgproxy.salt%'

    # Filter Config Converter
    ThreeBrs\ImgproxyBundle\Imagine\Filter\FilterConfigConverter:
        arguments:
            $filterConfig: '@liip_imagine.filter.configuration'

    # Cache Resolver
    ThreeBrs\ImgproxyBundle\Imagine\Cache\Resolver\ImgproxyCacheResolver:
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'imgproxy' }
